version: "3.7"

services:
  backend:
    build: app/backend
    image: prime
    ports:
      - "81:8081"
  frontend:
    build: app/frontend
    image: webapp
    ports:
      - "80:8080"
    #volumes:
    #  - .app/frontend:/go/src/mtekeli.io/go-micro/app/frontend
